// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.persistence;

#nullable disable

namespace backend.persistence.Migrations
{
    [DbContext(typeof(TankxContext))]
    partial class TankxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.domain.entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FinishedAt");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("GameMode");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("MapName");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("Region");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("WinnerId");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Matches_Region");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("backend.domain.entities.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("Accuracy");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("Deaths");

                    b.Property<bool>("Disconnected")
                        .HasColumnType("boolean")
                        .HasColumnName("Disconnected");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("Kills");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("MatchId");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("Position");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("Score");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("MatchId", "ProfileId")
                        .IsUnique();

                    b.ToTable("MatchParticipants", (string)null);
                });

            modelBuilder.Entity("backend.domain.entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("DisplayName");

                    b.Property<string>("TankType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("TankType");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("backend.domain.entities.Match", b =>
                {
                    b.HasOne("backend.domain.entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("backend.domain.entities.MatchParticipant", b =>
                {
                    b.HasOne("backend.domain.entities.Match", "Match")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.domain.entities.Profile", "Profile")
                        .WithMany("MatchParticipants")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.domain.entities.Match", b =>
                {
                    b.Navigation("MatchParticipants");
                });

            modelBuilder.Entity("backend.domain.entities.Profile", b =>
                {
                    b.Navigation("MatchParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
